### ISSUE TITLE
Suggestion chip title length

### ISSUE THREAD

**Issue by zehrasubas** [actions-on-google/actionssdk-updates-nodejs#1]
Hello,

In aog-webhook.js file the value of DAILY_NOTIFICATION_SUGGESTION parameter is 'Register for daily updates'. I was getting error as 'suggestion chip can not contain more then 25 characters'. After shrinking that text it worked.

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.

**Comment by findzaatar** [comment]
We're working on a fix for this, thanks for reporting!

**Comment by findzaatar** [comment]
Closing, fixed now!
