### ISSUE TITLE
The intent the app is registering updates for is not found

### ISSUE THREAD

**Issue by zehrasubas** [actions-on-google/actionssdk-updates-nodejs#2]
Hello,

When I choose to hear most recent tips I'm getting this error: The intent the app is asking for permission to send updates for is not found.

It's giving error on this part:

function askPermissionToNotify(conv) {
  // NOTE: User notification must be first enabled in the Actions Console.
  // Actions -> <Action> -> User updates and notifications.
  conv.ask(new UpdatePermission({intent: 'tell.latest.tip'}));
}

However,  tell.latest.tip is defined in the json file (didn't change anything from orj).

**Comment by JohannesMaier** [comment]
Hi, 
did you found a solution for this error? I got the same error.

**Comment by zehrasubas** [comment]
Hi,
Yes I did, you need to define Content title for update from AoG console-> Actions-> Select related intent -> Define content title under User Engagement

**Comment by JohannesMaier** [comment]
Thanks @zehrasubas this worked for me! 👍
