### ISSUE TITLE
Daily update personalization not working

### ISSUE THREAD

**Issue by adambezecny** [actions-on-google/actionssdk-updates-nodejs#4]
hi,

registering daily update is done by following code:

  conv.ask(new RegisterUpdate({
    intent: 'tell.tip',
    arguments: [{name: Parameters.CATEGORY, textValue: category}],
    frequency: 'DAILY',
  }));

i.e. category parameter is included as personalization example.  

Tell tip intent handler is defined as follows (in aog-webhook):

app.intent('tell.tip', (conv) => {
  return tellRandomTip(conv);
});

i.e.  **category is not in callback signature and not propagated into tellRandomTip call thus always getting random tip (not from selected category).** 

Can the sample code be amended so that:

**1. daily tip category is propagated correctly
2. personalization is applied also for push notification (i.e. alert on latest tip).**

I was trying to implement locally both above scenarios but I am always getting category=undefined in my handler. I am just wondering whether this feature of AoG SDK works correctly.

This is my extension for push notifications

1. added category parameter in action pkg for tell latest tip intent

      {
        "description": "Tell the latest tip",
        "name": "Tell latst tip",
        "fulfillment": {
          "conversationName": "tellLatestTip"
        },
        "intent": {
          "name": "tell.latest.tip",
          "parameters": [{
            "name": "category",
            "type": "org.schema.type.Text"
          }],
          "trigger": {
            "queryPatterns": [
              "the latest tip"
            ]
          }
        }
      },

2. update UpdatePermission call

  conv.ask(new UpdatePermission(
    {
      intent: 'tell.latest.tip',
      arguments: [{name: Parameters.CATEGORY, textValue: 'adam was here'}]
    }
  ));

3. extended intent handler signature (tellLatestTip)

function tellLatestTip(conv, category) {
  console.log('tellLatestTip ');
  console.log('category=' + category) // still getting category = undefined
  return getLatestTip()

**Comment by adambezecny** [comment]
just for better understanding of my changes described above see the commit in forked repository:
https://github.com/adambezecny/actionssdk-updates-nodejs/commit/1e04ee500a50df90e40a054ba64f6cf640d1e288

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
