### ISSUE TITLE
is actions.intent.CONFIGURE_UPDATES needed?

### ISSUE THREAD

**Issue by adambezecny** [actions-on-google/actionssdk-updates-nodejs#5]
hi,

intent actions.intent.CONFIGURE_UPDATES is defined in action package only. there is no handler for this intent in aog-webhook. Is this intent actually needed? From documentation it is not quite clear for whate xactly it should be used. When i removed it from action package and re-deployed the skill it was still working, i.e. user selects suggestion chip Daily updates -> askCategoryForDailyUpdates is called and renders categories + sets conv.data[ASK_CATEGORY_FLAG] to true -> user selects category -> handleRawInput is called -> registerForDailyUpdates -> conv.ask(new RegisterUpdate({ ... -> daily update helper is started. 

So why is actions.intent.CONFIGURE_UPDATES actually neeeded?

**Comment by maaaaaaaax** [comment]
Due to more than 3 months of inactivity, this issue is being closed. 

If you think the resolution is in error, please re-open the request with fresh information.
